### ISSUE TITLE
Settings:Grbl Tab not showing all parameters

### ISSUE THREAD

**Issue by glct12fsl** [terjeio/ioSender#101]
Hello,
i am using a grblHAL Teensy controller on a laser engraver and suddenly 
the Setting:Grbl Tab is not showing as grouped settings, but in a raw form and
also not showing some settings names.
I downloaded again ioesender and launched it, but no cure.
Also i flashed a prebuid hex from Phil Barrett configurations, but no cure.

**Comment by terjeio** [comment]
Which controller build and is ENUMS available? See _Help > About_:

![image](https://user-images.githubusercontent.com/20260062/118394000-6267d200-b642-11eb-98d0-573941bfdf76.png)

**Comment by glct12fsl** [comment]
Hello,
this is a snapshot of iosender info.
![Capture4](https://user-images.githubusercontent.com/58692166/118394212-ef635900-b64b-11eb-8f29-cbfaf58122a3.PNG)

**Comment by raenji-sk** [comment]
Don't know if something changed since I flashed the Teensy about a month or two ago. I did flash the pre built hex first and did not see all options in the Iosender config. Apparently the prebuilts are a bit old.

After compiling and flashing a hex from the latest source (the new repository, with separate core and drivers) files it all started to work perfectly.

**Comment by glct12fsl** [comment]
Also snapshots of the tab.
![Capture1](https://user-images.githubusercontent.com/58692166/118394260-48cb8800-b64c-11eb-84a4-b654139f4b82.PNG)

![Capture](https://user-images.githubusercontent.com/58692166/118394255-41a47a00-b64c-11eb-9573-aa842ef57006.PNG)
![Capture2](https://user-images.githubusercontent.com/58692166/118394264-4f59ff80-b64c-11eb-9b2a-1c313ddead57.PNG)
![Capture3](https://user-images.githubusercontent.com/58692166/118394270-554fe080-b64c-11eb-9716-9e683660889a.PNG)

**Comment by terjeio** [comment]
That is an old version from last year. Grouped (ENUMS) settings info was not available from the controller then, if not available the old style settings view is used and some may be missing. Recompile with the latest version, preferably from the [new repo](https://github.com/grblHAL/iMXRT1062).

**Comment by glct12fsl** [comment]
@terjeio and @raenji-sk  i followed your suggestion and the problem solved.
Thank you.
