### ISSUE TITLE
Stop during cycle and moving Z-Axis up (either with jog or with MDI window) randomly moves XY axis

### ISSUE THREAD

**Issue by manuel1139** [terjeio/ioSender#105]
When starting a cycle and you have to stop for any case, moving the Z Axis up leads to random movies in XY axis (which broke my small cutter ... )

Tried same code in bCNC worked nice.

**Comment by terjeio** [comment]
Which controller? Grbl or grblHAL based? Versions from _Help > About_ please.

**Comment by terjeio** [comment]
Closed due to lack of feedback.

**Comment by jappiemike** [comment]
I've also noticed this behavior using IOSender 2.0.35 and grblhal from 19/9/21.
