### ISSUE TITLE
Use telnet connection to esp32grbl?

### ISSUE THREAD

**Issue by whoim2** [terjeio/ioSender#112]
Possible?

**Comment by terjeio** [comment]
Both telnet and websocket connections should work. IIRC websocket uses port 81? I have never tested it though.

The [grblHAL driver](https://github.com/grblHAL/ESP32) supports both, now even FTP up/download to SD card if enabled.

**Comment by whoim2** [comment]
Not have info now, wait hardware shipping.. i need heightmap for create pcb, and wireless connection. USB connection very unstable, bluetooth too. 
Esp32grbl may use gcode from sd, but not have heightmap algorithm. 

Ok, im try as get boards, thanks!
