### ISSUE TITLE
Crash after M0 m-code

### ISSUE THREAD

**Issue by kfmut** [terjeio/ioSender#114]
Hi,

I'm doing some tests of macros functionality and noticed that program pause issued with M0 m-code results in crash right after I hit `Cycle Start`. Single issued M0 m-code also results in crash after `Cycle Start`. Verbose output on console before crash doesn't show anything interesting, just `Hold` state.

ioSender version is 2.0.33

Macro I was testing:
```
G21
G94
G90
G53 G0 Z-1
G53 X-300 Y-354
M0
G53 X-150.5 Y-1
G53 G1 Z-84 F500
```

**Comment by terjeio** [comment]
Yep, that is a bug. Fixed in next release - I'll see if I can publish it today.

**Comment by kfmut** [comment]
@terjeio

Great!

Further testing revealed that if ioSender is loaded with a program and macro with M0 is invoked, program is automatically started right after the macro. Will it be fixed too?

**Comment by terjeio** [comment]
I think so, can you test with the [34p1 edge version](http://www.io-engineering.com/downloads)?

**Comment by kfmut** [comment]
@terjeio 

Yep, it's works but `ok` response from macro commands are assigned to blocks of loaded program, but definetly no crashes in this version :-)

![Screen-2021-07-04_18-54-41](https://user-images.githubusercontent.com/29616141/124391510-9766db80-dcf9-11eb-94eb-576d142af045.png)

**Comment by terjeio** [comment]
> Yep, it's works but ok responses from macro commands are assigned to blocks of loaded program, but definetly no crashes in this version

This should be fixed in the lates release.
