### ISSUE TITLE
Trimatic tab not showing up

### ISSUE THREAD

**Issue by Cncninja** [terjeio/ioSender#128]
I have 2209s installed and it shows the trinamic 0.05 plug-in loaded via the console but no tab is loading in the GUI. I'm sure this is an operator error but if you could point me in the right direction... thank you so much for all your hard work!!

**Comment by Cncninja** [comment]
i just relized the 2209 is uart not spi... So i guess this will not work with grblhall and a skr1.4turbo ill look at buying some 2130s

**Comment by terjeio** [comment]
You must enable at least one Trinamic driver with [$338](https://github.com/grblHAL/Plugins_motor#settings) before it shows up.

> i just relized the 2209 is uart not spi... So i guess this will not work with grblhall and a skr1.4turbo ill look at buying some 2130s

From the SKR schematic it seems UART mode drivers are not supported. Either you'll have to run them in non-UART mode or switch to compatible SPI mode drivers.

**Comment by Cncninja** [comment]
the skr1.4 does support uart mode drivers.  but not sure grblhal with the current lpc17XX driver does

**Comment by Cncninja** [comment]
![ice_screenshot_20210906-215713](https://user-images.githubusercontent.com/75448047/132286830-f6788101-cf1a-44ed-94e1-3455f8f08c8f.jpeg)
![ice_screenshot_20210906-215746](https://user-images.githubusercontent.com/75448047/132286851-8c9f5ab1-08f8-4c66-bb2c-e062f9756f82.jpeg)
![ice_screenshot_20210906-215823](https://user-images.githubusercontent.com/75448047/132286868-6fc3a36c-49e0-40e5-a442-602464063f9a.jpeg)

![ice_screenshot_20210906-215903](https://user-images.githubusercontent.com/75448047/132286876-c0f1fd40-d388-490f-a8a6-027dd5a88e5c.jpeg)

**Comment by terjeio** [comment]
>  but not sure grblhal with the current lpc17XX driver does

It does not - you'll have to add low-level UART driver code for that. Likely that has to be a software UART for each axis? I've got no idea of how much work that would be... Perhaps Marlin has code that can be transplanted?

**Comment by Cncninja** [comment]
Thank you for the reply and your hard work.. i just got the wrong drivers. ill look at getting some 2130's or just running these in step/dir mode

Thank you again

**Comment by terjeio** [comment]
FYI soft UART support was added to the LPC17xx driver in january.
