### ISSUE TITLE
Req: The ability to set different distances and feedrates for the Z axis vs XY Axis

### ISSUE THREAD

**Issue by timm052** [terjeio/ioSender#134]
Having the jogging distances and feed rates be a universal setting for all axises makes it very easy to crash your Z-axis into stock by accident when jogging into position. Other g code senders address this by allowing different settings for the z-axis so you can keep your z-axis on 1mm while the x and y can be jogged at 10mm+ I think this would be a useful addition particularly for people using gamepads to jog the machine around.

**Comment by terjeio** [comment]
ioSender has continuous jogging when using the cursor keys except when the <CTRL> modifier is pressed for step jogging. Step jogging distance is typically 1mm or less (can be changed on the fly), other jogging distances should typically be set to at least the length of the longest axis. If the controller is grblHAL based and the machine is homed (and proper travel distances are configured) you may also set $40 to limit jogging to always be within machine limits.

Continuous jogging = only a single jog command with a long distance is issued on key down, and a jog cancel is issued on a key up. This means that the distance is in practice not limited by the settings but rather by how long they key is pressed.

I assume the gamepad simulates pressing the cursor keys to jog, so the same applies to that.

The [wiki](https://github.com/terjeio/ioSender/wiki/Usage-tips) lists keyboard shortcuts available.
