### ISSUE TITLE
Machine not following toolpath

### ISSUE THREAD

**Issue by stevempotter** [terjeio/ioSender#142]
I was trying to face my spoilboard yesterday and was surprised to see the cutter not following the toolpath that was displayed correctly in the live preview window. The red dot, and the spindle, were way off course and had to be stopped.  I tried updating to the latest executable (x.35) but that did not fix it. The problem did not occur exactly the same on different attempts.
Could it have been because I had ticked the "Aggressive buffering" option? I unticked it and the problem seems to be gone, but I remain wary. I am using grblHAL on Phil Barrett's Teensy 4.1 and an ethernet link between IOsender and the control board.
Can you think of any reasons why a toolpath that is correctly loaded and displayed is not followed?

**Comment by terjeio** [comment]
I guess this issue has been resolved, reopen if not.
