### ISSUE TITLE
In Windows 7 buttons are not visible on a Probing tab.

### ISSUE THREAD

**Issue by AndWalu** [terjeio/ioSender#174]
Windows 7, ioSender 2.0.35
On the Probing tab the buttons are placed outside the frame, they cannot be pressed with a mouse but using Tab and Enter they can be.

![ioSender-Probing](https://user-images.githubusercontent.com/16928414/145270928-756010a3-498a-4c11-9481-6e4fb91b3d2f.jpg)

**Comment by terjeio** [comment]
Can you try the latest [edge version](http://www.io-engineering.com/downloads)?

**Comment by AndWalu** [comment]
> Can you try the latest [edge version](http://www.io-engineering.com/downloads)?

Thank you, this version works.
