### ISSUE TITLE
Using a jogwheel possible? 

### ISSUE THREAD

**Issue by moelski** [terjeio/ioSender#183]
Hi !

I´m using estlcam at the moment and mostly happy with it. But especially the CAM part is not the best so I would try something different. grblHal may be a solution for combined with iosender. But there is one peace missing - at least for me. The jogwheel. 

As some of you may know estlcam has direct support for it. And to be honest I love it. It makes driving my machine so much easier. My keyboard is not always direct accessible so using a jogwheel is a must for me. 

Question is .. Is there any chance to add a jogwheel to iosender? 
Are there any plans to implement it? 
Since I am a .net dev myself I could assist in adding a jogwheel to ioSender ? 

regards
  Dominik

**Comment by terjeio** [comment]
> Question is .. Is there any chance to add a jogwheel to iosender?

I do not have one and do not plan to get one so someone else has to do that.

> Are there any plans to implement it?

No. What I am working on now is to enhance support for keypads/MPGs connected to the controller via additional input port(s).

> Since I am a .net dev myself I could assist in adding a jogwheel to ioSender ?

Yes, do you have a protocol description for the one you have.
