### ISSUE TITLE
Error message readability

### ISSUE THREAD

**Issue by calabr** [terjeio/ioSender#186]
It's related to version 2.0.34, 2.0.35
 Programm loadting error window apear with error description in the window header.
It's not alweys wisible and hard to understand what is the problem
![Capture_1](https://user-images.githubusercontent.com/64111035/149671548-39559074-c61e-4782-bc4f-d366451c2f8a.JPG)
 Suggests to set "G-code Error" as the window name and move error description inside the window.

**Comment by terjeio** [comment]
Fixed in 2.0.36p28 edge version.
