### ISSUE TITLE
Nothing happens when iosender.exe is clicked

### ISSUE THREAD

**Issue by DavidR8** [terjeio/ioSender#188]
Running Win10, downloaded the most recent version, unzipped, clicked on iosender.exe. Message that no config file exists do I want to create a new one. I click yes. Nothing further happens.
With Task Manager open clicking on iosender.exe again I see the app in the list then it says suspended and disappears.
I have no idea how to actually get the app running.

**Comment by calabr** [comment]
Do you have any com port in the system when starting application?
It's bug in software 
https://github.com/terjeio/ioSender/issues/149#issuecomment-965487685
which can correlate with yours.

**Comment by DavidR8** [comment]
@calabr I figured it out. I needed to actually have a suitable board connected.

**Comment by Guenni75** [comment]
How can i start without a connected board???????

**Comment by calabr** [comment]
> How can i start without a connected board???????

 It's not supported. 
You can try to use simulator, but you should compile it yourself.
[grbl-sim](https://github.com/grblHAL/Simulator)
