### ISSUE TITLE
Crashing after a second

### ISSUE THREAD

**Issue by snakescb** [terjeio/ioSender#189]
Hi, I am trying to use ioSender 2.0.35 on a FluidNC controller [(see here)](https://github.com/bdring/FluidNC) . The window opens, shows correct DRO information, but then crashes after a second or so. I already tried to increase the StartupDelay to 5 seconds, with no change. On the edge version i receive below error message, which does not mean a lot to me unfortunately. Also the -isLegacy option does not change anything. I also ways playing around with locales and languages, did not change anything as well unfortunately.

Maybe FluidNC cannot be supported now, is anybody using ioSender with FluidNC? Would be nice if it works, from what I saw so far, the best grbl sender out there!

![Screenshot 2022-01-19 100143](https://user-images.githubusercontent.com/10495848/150098077-55f044e3-e44c-44de-8c41-764150c0e79e.png)

**Comment by terjeio** [comment]
Is FluidNC returning data that is not compatible with the legacy Grbl format specification? On startup only? The ESP32 guru is also a very annoying in that a lot of noise is typically generated by him on startup (and is the reason for the option to set a long wait so it can be ignored).

If you try to connect with "No action" or via Bluetooth/Wifi does that change the response? If via Bluetooth/Wifi at least the guru is usually silenced...

![image](https://user-images.githubusercontent.com/20260062/150206303-301e7eb3-6693-43bf-8623-8c8a9b45b72b.png)

Note that I have written this sender primarily to support many of the new features of [grblHAL](https://github.com/grblHAL), legacy Grbl is supported but will be limited as some advanced functionality, such as tool change support, cannot be enabled.
