### ISSUE TITLE
Legacy Grbl Keyboard jogging 2.0.36 XL

### ISSUE THREAD

**Issue by phil-barrett** [terjeio/ioSender#196]
Keyboard jogging does not work when 2.0.36 XL is connected to legacy Grbl.  It worked with earlier edge versions though I have not tested in at least a month.

**Comment by terjeio** [comment]
I forgot to copy some code to the XL version when refactoring jogging. I have uploaded a [edge version](http://www.io-engineering.com/downloads) with this in place.

**Comment by phil-barrett** [comment]
Thanks!  I'll give it a try in a while (have to set up a legacy test bed or go into the makerspace). I'll let you know if it fixes.
