### ISSUE TITLE
Gcode lines getting skipped

### ISSUE THREAD

**Issue by Bert911** [terjeio/ioSender#207]
I'm not sure what's going on, so I made a video to show you the problem.
I think that some gcode lines are getting skipped.

[Video](https://youtu.be/_JAP9u7-7Qk)

To be clear, this problem happened not every time I started the cycle.
Just by stopping the cycle and restarting it, the problem happened like 75% of the time the other 25% it worked just fine. I tested it around 50 times. It happened with the 2.0.37p1/2.0.36 but not with the 2.0.35 version of iosender. A full reset of the teensy and the iosender didn't change anything.

And one drilling operation of two holes ended up by drilling one hole two times.

Besides that I also got the error:33, error:36 and one time even error:2 in different gcodes and sometimes different errors or no error in one gcode then I ran the program multiple times.
By changing minimal things like radii or distances the gcode files sometimes worked, sometimes they didn't. The marked lines from the errors didn't differ from the other ones above or below.

Is it possible that this could be caused by a bad Ethernet connection or something related to the transmission.

A problem with the internal grblhal should reproduce the problem every time I guess as well as the iosender.

Everything I tried changing at fusion 360 didn't help.
Then I'm remembered correctly since I updated grblhal I didn't run a program to verify if it's a sender or a grblhal problem or both.

The gcode from the video and from the boring.
[OneHoleTwoTimes.txt](https://github.com/terjeio/ioSender/files/8092767/OneHoleTwoTimes.txt)
[RadialDesaster.txt](https://github.com/terjeio/ioSender/files/8092768/RadialDesaster.txt)
![error33](https://user-images.githubusercontent.com/94561142/154585694-d93c96f9-5a11-45ae-b78a-250b880b313f.PNG)

**Comment by phil-barrett** [comment]
Hmmm, are you using telnet or websocket?  There was a telnet bug reported that was causing comm errors, iirc. If you are using prebuilt binaries, they might be older than that.  If telnet, try websocket.

**Comment by Bert911** [comment]
Websocket solved the problem.
Thx a lot.
