### ISSUE TITLE
Settings: Grbl descriptions missing

### ISSUE THREAD

**Issue by phil-barrett** [terjeio/ioSender#211]
I've checked 3 machines here with fairly recent versions of ioSender (inlcuding most recent edge version and 2.0.36 release) and none of them are showing any Grbl settings descriptions.

Going back over previous versions 2.0.31 and 2.0.33 show descriptions. 2.0.35 and 2.0.36 do not. Localization related?

**Comment by terjeio** [comment]
Works for me with the latest edge version.

**Comment by phil-barrett** [comment]
OK, so what am I doing wrong?  None of the machines I have installed it on show the descriptions.

**Comment by terjeio** [comment]
![image](https://user-images.githubusercontent.com/20260062/155851548-6cc9eec7-d547-4758-b65e-7f16a10e5cac.png)

Do you have `SED` in the options list as shown above?

There is a #define setting for not compiling with settings descriptions, used for two controllers with limited flash - `NO_SETTINGS_DESCRIPTIONS`. What is odd is that this is set as a build option in Eclipse, it is not defined anywhere in the source code.

Do you get any response if requesting a settings description from the controller? Try with `$SED=0` from a terminal, you should get this response:
`[SETTINGDESCR:0|Sets time length per step. Minimum 2 microseconds.\n\nThis needs to be reduced from the default value of 10 when max. step rates exceed approximately 80 kHz.]`

**Comment by phil-barrett** [comment]
No, I have
`[NEWOPT:ENUMS,RT+,ES,TC,ETH,FTP,SD]`

I get error 2 with $SED=0

**Comment by phil-barrett** [comment]
Note, against the same grblHAL build, 31 and 33 work correctly.

**Comment by terjeio** [comment]
Which version of grblHAL? $I output?

**Comment by phil-barrett** [comment]
```
[VER:1.1f.20210715:]
[OPT:VNMSL+,999,1024,5,0]
[NEWOPT:ENUMS,RT+,ES,TC,ETH,FTP,SD]
[FIRMWARE:grblHAL]
[NVS STORAGE:*FLASH]
[DRIVER:iMXRT1062]
[DRIVER VERSION:210725]
[DRIVER OPTIONS:USB.2]
[BOARD:T41U5XBB]
[AUX IO:1,3,0,0]
```

**Comment by terjeio** [comment]
OK, that explains it. `$SED` was added in late august last year. It is possible to add a settings definitions file to the sender folder from an earlier version or from saving it from the Config App - but better just to upgrade?

**Comment by phil-barrett** [comment]
The problem with upgrading grblHAL is that people in the field have a working CNC machine.  Why force them to upgrade the machine?  Wouldn't it be better to make newer versions of ioSender work without forcing the user to do anything?

I need to check but I think this is an issue with legacy 8-bit Grbl, too.  I recall not seeing descriptions on the NEMS machine prior to upgrading it to grblHAL.

**Comment by terjeio** [comment]
> Wouldn't it be better to make newer versions of ioSender work without forcing the user to do anything?

Foe the user yes - but not for me. I now have functionality in place that allows me to add settings, alarms and error codes to grblHAL (including plugins) without requiring updates to the sender - so it goes both ways. I have spent a fair amount of time to achive this - and I am a bit reluctant to spend more by keeping backwards compatibility with older versions for non critical functionality as I regard this to be.

> I need to check but I think this is an issue with legacy 8-bit Grbl, too. I recall not seeing descriptions on the NEMS machine prior to upgrading it to grblHAL.

This should read settings info from a file. Note that the settings treeview is not available for legacy Grbl and I have no intention to add support for that. BTW I see now that I have not included the legacy Grbl .csv-files in the XL build - will add those in the next.

**Comment by terjeio** [comment]
I have uploaded a new XL edge version with the missing legacy Grbl files and a version of a grblHAL settings definitions file - hopefully the last I hand edited (copied from the standard version). You may get settings descriptions for some/most of the settings with this. If not I'll have to revert to older versions to debug and fix...
