### ISSUE TITLE
Help with building

### ISSUE THREAD

**Issue by Henrikastro** [terjeio/ioSender#213]
So, I'm a complete noob in C# and im having trouble building the source code. And I have a couple of questions

1-Am I supposed to be building on the ioSender.sln right?
2-If I got it correctly, I should install Helix 3D toolkit on all .sln that use it?
3-The Vector3D library, I need to build it in the ioSender folder and then add the dlls that I get from as references? Do they need to be in any specific folder?
4-Should I add as reference the dlls for the Vector3 library and the WPF toolkit for each sln?

**Comment by Henrikastro** [comment]
So, I believe i have done cleared all the dependecies but right now i'm dealing with a bunch of missing files errors when compiling, is it something wrong that i have done with the dependecies or is it something else? 

![image](https://user-images.githubusercontent.com/37155325/158204487-6fddb005-e34d-4870-bb92-04762a394136.png)

**Comment by terjeio** [comment]
> 1-Am I supposed to be building on the ioSender.sln right?

Yes. But unless you need to change anything you can just use the prebuild binaries.

> 2-If I got `it` correctly, I should install Helix 3D toolkit on all .sln that use it?

No, one instance is enough. IIRC it is only referenced by the _CNC GCodeViewer_ project - which is in turn referenced by the _ioSender_ project.

> 3-The Vector3D library, I need to build it in the ioSender folder and then add the dlls that I get from as references? Do they need to be in any specific folder?

I have one instance in the same folder as the the other the projects.

> 4-Should I add as reference the dlls for the Vector3 library and the WPF toolkit for each sln?

No, the references should all be ok as they are - but you may have to remove/add them in the projects they are referenced?

> So, I believe i have done cleared all the dependecies but right now i'm dealing with a bunch of missing files errors when compiling, is it something wrong that i have done with the dependecies or is it something else?

My best guess is that the references/dependencies are not ok. Can you build _CNC Core_ separately without errors? And then _CNC Controls_?

**Comment by Henrikastro** [comment]
CNC Core compiles successfully, but I still get the missing files error when trying to compile CNC Controls

**Comment by Henrikastro** [comment]
Let me try to build from scratch having your answers in mind and then I'll come back to you

**Comment by Henrikastro** [comment]
Just to answer you, yeah i plan editing the code, and if maybe there was some way I could contact you I would have some offers to make to you.

So, with a fresh master downloaded, firstly using nuget I installed the HelixToolkit.Wpf file to the ioSender .snl. Then I put both the folders RP.Math and RP.Math.Vector3 (which are the two that I believe that are being used here) in the master folder, and them added both of the .csproj to the project.

 Then, if my interpretation of your building section was correct, I put the Xceed.Wpf.Toolkit dll in the master folder, where the readme is, but im not sure about this one. Then I added the websocket folder to the master folder and included the .csproj to the project. And then finally, I added the 4 Aforge.dll that are used (aforge, aforgecontrols, videodirectshow and video). 

If i hit compile at this point all the dlls are not getting found, hitting me with a bunch of warnings, including one for the helixtoolkit in the controls probing and gcodeviewers so I install it on both of them to fix and then I manually reference the right dlls to their correct places. After this, I end up at the same place I was above, did I miss any steps?

**Comment by Henrikastro** [comment]
Sooooo....

It turns out that those files are actually missing lol, I tried to compile the 2.0.35 version and it worked just fine, maybe you forgot to add those files to the source version of the release? Anyways, thank you for the attention and let me know if this was actually the case.

**Comment by terjeio** [comment]
> It turns out that those files are actually missing lol

Oops, I'll have to script updating this repo as well... I keep the master in a local subversion repo so I am not that familiar with git.

I have now added the files.

>  if maybe there was some way I could contact you

terjeio@online.no

**Comment by Henrikastro** [comment]
Finally able to build it, thank you so much!

**Comment by olijouve** [comment]
@Henrikastro your changes might be good for other users.
As you told you were not familiar with git do not forget to fork the project, commit your changes and to ask for a pull request.
