### ISSUE TITLE
When building a surface map, the controller hangs accidentally

### ISSUE THREAD

**Issue by Maksko** [terjeio/ioSender#217]
When building a surface map, the controller hangs accidentally. The CurrentDomainException window appears: "Unhandled exception occured". Program version Release 
ioSender 2.0.37. Makerbase MKS DLC32 controller, FluidNC firmware v3.4.2. Wifi connection.
Where do I look for error?

**Comment by terjeio** [comment]
I have run a few thousand probing actions over USB with no issues. Can you try with the [latest edge version](http://www.io-engineering.com/downloads).

**Comment by terjeio** [comment]
The latest [edge versions](http://www.io-engineering.com/downloads) has been improved to tolerate more badly formed/corrupted reports from the controller. They will silently be ignored.
