### ISSUE TITLE
Localization/translation uk-UA

### ISSUE THREAD

**Issue by calabr** [terjeio/ioSender#220]
Ukrainian translation uk-UA based on ioSener Edge 2.0.38p1
Updated
[translation-uk-UA.txt](https://github.com/terjeio/ioSender/files/8502249/translation-uk-UA.txt)

**Comment by terjeio** [comment]
Thanks, now added to [latest edge version](http://www.io-engineering.com/downloads).

**Comment by calabr** [comment]
Updated to 2.0.38
[translation.txt](https://github.com/terjeio/ioSender/files/8711929/translation.txt)
p
