### ISSUE TITLE
COM port error

### ISSUE THREAD

**Issue by tetref** [terjeio/ioSender#230]
Probably since version 2.0.37, ioSender has a special error when creating a default configuration. After editing App.config to:

**_<PortParams>COM6:115200,N,8,1</PortParams>_**

 everything works. This may apply to specific Windows language versions ..
![error_iosender](https://user-images.githubusercontent.com/11065044/174047424-b3b5eb30-186f-41f5-89ca-b4a2ae773b2b.jpg)
![ioSender_error](https://user-images.githubusercontent.com/11065044/174047448-06945c54-c298-43d8-b6a6-1042d794c1f3.jpg)

**Comment by terjeio** [comment]
Can you try the latest [edge version](http://www.io-engineering.com/downloads)? It looks like there is a superfluous space after the reported com port name messing up.

**Comment by tetref** [comment]
2.0.41p2 Edge - left picture NOT WORKS
2.0.41p2 XL Edge - right picture - WORKS


![ioSender_2 0 41p2](https://user-images.githubusercontent.com/11065044/186087505-16c9eb33-e934-4c79-a9d5-761ce4050e45.png)

**Comment by terjeio** [comment]
Looks like the update somehow went wrong, I have now uploaded a new edge version that should be ok.

**Comment by tetref** [comment]
You can close this thread, both 2.0.41p3 versions are working now.
