### ISSUE TITLE
Possible licence issue with `Xceed.Wpf.Toolkit`

### ISSUE THREAD

**Issue by FroggieFrog** [terjeio/ioSender#231]
Because you are using a version > `3.8` of the `Xceed.Wpf.Toolkit` there could be an issue with the licence.
See this issue where the maintainer **does not** deny the issue: [xceedsoftware/wpftoolkit#1598](https://github.com/xceedsoftware/wpftoolkit/issues/1598)
At least your distributed version `2.0.38` contains `Xceed.Wpf.Toolkit.dll` in version `4.0.0.0`

Do you have other/additional information on this topic?

**Comment by terjeio** [comment]
Oops - I was not aware of these requirements. I have removed all binary releases and will soon replace the color picker control that was used. I am sorry about this mistake.

**Comment by terjeio** [comment]
Dependency has now been removed.
