### ISSUE TITLE
ioSender 3D Viewer shows curves as straight lines // fixed but not official released yet

### ISSUE THREAD

**Issue by mintracer** [terjeio/ioSender#235]
Hi all!

yesterday i wanted to mill an easy contour...- but in ioSender the some curves are showing as straight lines... 

i tried in cncJS and there the curves are curves... 

maybe just a user error :)

see attached screenshots and the used gcode...

thanks for watching and great project!

![Screenshot 2022-07-12 204622](https://user-images.githubusercontent.com/97637453/178699406-6baa14da-7e74-42b4-befc-bf7501a571ff.png)
![Screenshot 2022-07-12 204716](https://user-images.githubusercontent.com/97637453/178699412-ab6648a2-1a76-4cb0-9186-394dc7160d16.png)
[harley_grblHAL_kontur_xcarve.gcode.txt](https://github.com/terjeio/ioSender/files/9100834/harley_grblHAL_kontur_xcarve.gcode.txt)

**Comment by terjeio** [comment]
Those curves are in fact made up of many small line segments and an optimization (for reducing the amount of points to plot) is buggy.
I believe I have fixed this and uploaded a [new edge version](http://www.io-engineering.com/downloads) with the fix for you to try.

**Comment by phil-barrett** [comment]
I ran into this also.  Are you planning a quick update to the released version? Some of the 3D displays are really off - I thought my GCode generation was messed up. I would not want new ioSender users to see that.
Here is an example. The bottom is the actual tool path (it cuts correctly).  The top is ioSender 3D view.
![image](https://user-images.githubusercontent.com/16570958/179364184-dc2ed02d-9a3c-4be6-9dce-7fda1b7d30cf.png)

**Comment by mintracer** [comment]
reopened to inform new user that a fix is already coming.. :) / the linked Version 2.0.40.p2 fixed it for me... :)

**Comment by phil-barrett** [comment]
thanks.  The edge version works correctly for me too.

**Comment by phil-barrett** [comment]
Thank you!!!
