### ISSUE TITLE
Spindle RPM not updating when changed

### ISSUE THREAD

**Issue by Dietz0r** [terjeio/ioSender#236]
Hey there,
i'm currently brining a machine to life with grblHAL and noticed this odd behaviour in ioSender.

When the spindle is running and i want to change the spindle rpm i have to  either use the MDI command line ( e.g.: S12000 ) or put the spindle on off and back to CW as fast as i can so it sends the new speed to the spindle.

Is this wanted behaviour or a bug? I expected it to change the RPM after hitting enter or leaving the field.
Running the latest version of XL and tested in normal too.

Thanks for the awesome sender! It's a joy to work with.

**Comment by terjeio** [comment]
Can you try the [latest edge version](http://www.io-engineering.com/downloads)?

**Comment by Dietz0r** [comment]
Just tried the edge version.

the field now sends the proper S command when enter is pressed.

thank you very much!
