### ISSUE TITLE
common application shortcuts

### ISSUE THREAD

**Issue by kimstik** [terjeio/ioSender#239]
It would be useful to handle some common application shortcuts by default.
Ctrl + O for new document opening for example.

**Comment by terjeio** [comment]
> Ctrl + O for new document opening for example.

Use Alt F L (or Alt F <enter>) to load a file. When you press the Alt key common shortcuts that can be used with the Alt key gets underlined in the menubar and the sidebar. You can also drop a file on the _Program_ list or _3D View_ to load it.
