### ISSUE TITLE
Y offset input box - difficult to enter negative number

### ISSUE THREAD

**Issue by 5ocworkshop** [terjeio/ioSender#240]
I recently moved my machine and had to resquare my X axis so I needed to put a negative value in the Y-offset box.  I was eventually able to do it by erasing the contents, putting in four digits of my positive value (2.86) and then arrow naviagting over and inputting the negative sign.

Others on the PrintNC Discord have surfaced initially saying "I can't input a negative value".

Not sure how to improve it (perhaps a radio box for sign?) but wanted to flag it.

**Comment by terjeio** [comment]
Can you try the latest [edge version](http://www.io-engineering.com/downloads)? Is this better?

**Comment by terjeio** [comment]
Fixed in the latest release.
