### ISSUE TITLE
E-Stop Issue

### ISSUE THREAD

**Issue by silver2row** [terjeio/ioSender#241]
Hello,

I am receiving an E-Stop issue. I am a novice w/ this software so far and I just wanted to test it for now.

Anyway, here is the photo of my current issue. It keeps popping up.

![E-Stop](https://user-images.githubusercontent.com/9708195/185885894-95edfeb7-8488-4d20-acb4-61799cc95062.png)

Seth

P.S. I have nothing connected in the form of hardware yet. So, maybe this is the issue. I am just going over the source right now.

**Comment by andrewmarles** [comment]
You need to either connect a switch and close the e-stop, or else you can use a terminal program to access the controller and invert the control signal such as described [here](https://www.grbl.org/single-post/naked-teensy-party).

**Comment by phil-barrett** [comment]
Yes, ioSender won't start up with the E-Stop active. 

Another place to read up on this is in the [First Run wiki ](https://github.com/grblHAL/core/wiki/First-Run-Grbl-Settings) section.

**Comment by silver2row** [comment]
Hello @andrewmarles and @phil-barrett ,

Thank you guys. I will read more about the source soon. 

Seth
