### ISSUE TITLE
No color settings

### ISSUE THREAD

**Issue by zab-ig** [terjeio/ioSender#263]
Hello. I don't see color settings.
If you manually change the colors in the App.config file, they still do not display as they should, and after closing the iosender, the color settings in the App.config file are reset to default.
![iosender](https://user-images.githubusercontent.com/78402261/209497984-86ab2d92-d79d-476f-aa03-f86fdd2a0874.png)

**Comment by terjeio** [comment]
Remove the ScA, ScR, ScG and ScB elements from the XML to set the RGB color.
I'll have to find or write a new color selector as the one I used originally had an odd license...

**Comment by terjeio** [comment]
Fixed in the latest release.
