### ISSUE TITLE
Hungarian translation

### ISSUE THREAD

**Issue by dobakszilard** [terjeio/ioSender#267]
Dear @terjeio  !

I made a Hungarian translation, could you include it in the next version?

Hungarian translation :

UTF-8

Locale\hu-HU

[translation.txt](https://github.com/terjeio/ioSender/files/10369177/translation.txt)

**Comment by terjeio** [comment]
Thanks, I have now uploaded a new [edge version](http://www.io-engineering.com/downloads) with the translation added.

And sorry for beeing a bit late with this, I have been away and not able to load your translation before now.

**Comment by dobakszilard** [comment]
Thank you very much!
