### ISSUE TITLE
Trouble running ioSender on fresh Win 11 install

### ISSUE THREAD

**Issue by axg20202** [terjeio/ioSender#275]
Is anyone aware of a reason why I can't launch ioSender on a new Win 11 machine? It doesn't even get to the connection settings window. No errror message, just doesn't launch. Running it as administrator from a folder on the host PC. Even a folder in Documents or on desktop, same result.  Any ideas?   I'm using the latest release, but same result with earlier releases. Runs fine on my other PCs with Win 11/10.

**Comment by terjeio** [comment]
Virus protection is blocking the sender? The code is not signed as it is quite expensive to buy the certificate needed.

**Comment by axg20202** [comment]
Sorted. Can't believe I didn't even think of that. Built in 'protection' that stops something running without any notification. Feel dumb for asking. Thanks.
