### ISSUE TITLE
3D view not rendering properly 

### ISSUE THREAD

**Issue by brex480** [terjeio/ioSender#276]
First off I'm sorry if I am missing an obvious step. I saw a section in the wiki which might be the answer and made sure what to do with it. Anywho, my issue is the 3d view panel is unusable. Rotating the image around I can see glimpse of the file but it is like the contrast is turned up all the way on an old tv. I have tried several different releases running on windows 11. Thank you

<img width="1280" alt="Untitled" src="https://user-images.githubusercontent.com/9660508/219434349-62402f7f-b22c-4e95-8edf-0d7376e34c9a.png">

**Comment by phil-barrett** [comment]
Try turning off the grid.
![image](https://user-images.githubusercontent.com/16570958/219455501-bfaf04a2-0cc8-4e6a-bf70-28f11ed863a9.png)

**Comment by brex480** [comment]
Should have mentioned I have tried toggling off and on all the buttons there and in the settings panel. I can see changes happening but always still blurred like looking through a extremely fine mesh.

**Comment by terjeio** [comment]
Have you checked _Black background_ in _Settings: App_? If so I have to find or write a new color picker for that to become useful.

**Comment by brex480** [comment]
In the first picture yes it was selected but that it not the cause of the underlying issue. He it is unselected.
<img width="1280" alt="1" src="https://user-images.githubusercontent.com/9660508/219480094-54c3da5f-0ccb-4982-91ab-fef10af23a34.png">

**Comment by terjeio** [comment]
Can you attach the file (zipped) to a comment?

**Comment by brex480** [comment]
Guessing you are asking for the gcode file. Its just something I popped out of fusion 360 real quick using openbuilds post to test out iosender. It opens fine in openbuilds control and gsender.  Also tried a file that came from openbuilds with the same results. 
[1001.zip](https://github.com/terjeio/ioSender/files/10760699/1001.zip)

**Comment by phil-barrett** [comment]
It works fine for me on Win 10 using 2.0.40 and 2.0.41 using default ioSender settings.
![image](https://user-images.githubusercontent.com/16570958/219488466-8b10825d-4367-4c81-83ff-fae507857a65.png)

**Comment by terjeio** [comment]
Renders ok for me, it seems there are many short movements so check _Min distance_ and possibly also _Arc resolution_:

![image](https://user-images.githubusercontent.com/20260062/219488465-7e34a550-1d1b-4eab-b1bf-e4e936b002c6.png)

**Comment by brex480** [comment]
> It works fine for me on Win 10 using 2.0.40 and 2.0.41 using default ioSender settings. Wonder if it's a graphics card issue? ![image](https://user-images.githubusercontent.com/16570958/219488466-8b10825d-4367-4c81-83ff-fae507857a65.png)

Winner winner, forced it to use the actual GPU and now works perfectly. Thanks for the help. I am loving iosender even when I couldn't get the viewer working.

**Comment by phil-barrett** [comment]
What exactly did you do?  (this is for others who run into similar situations)

**Comment by brex480** [comment]
On windows 11 you will go to display settings and click graphics. From there you will have to add iosender.exe to a list of applications. Then you can click the options menu next to iosender and select high performance. I have had to do it for other programs in the past but didn't cross my mind today.
