### ISSUE TITLE
Bug: pressing 0 for DRO on any axis in Probing tab causes DispatcherException

### ISSUE THREAD

**Issue by LoganFraser** [terjeio/ioSender#278]
Happens in 2.0.41 XL only (no DRO present on standard with probing selected)

Method to cause crash: 
open iosender
Select Probing tab
Press 0 next to any axis.
Result: DispatcherException.

**Comment by terjeio** [comment]
See issue #273 for resolution. I guess it is soon time to release a new build...

**Comment by LoganFraser** [comment]
Ah. Sorry for the duplicate post.  I did read through the issues but I somehow missed it.  I'll mark this closed.
