### ISSUE TITLE
Does ioSender work with Fluidnc ?

### ISSUE THREAD

**Issue by RDS356** [terjeio/ioSender#284]
Just a doubt, Does it work with Fluidnc ? I did a little test, but I could see that the jog works only in imperial mode. So I stopped the tests.
Regards,
Reinaldo de Souza

**Comment by terjeio** [comment]
AFAIK it is not Grbl compatible when it comes to settings handling - of which several are read on startup to configure the sender. So the sender will likely not work as it should. A possible workaround is to use the [grblHAL ESP32 driver](https://github.com/grblHAL/ESP32) instead.

**Comment by RDS356** [comment]
Ok, thank you.
I will try with grblhal esp32.
