### ISSUE TITLE
Spindle button functions but bounces back to previous state - Doesn't change state when running a program.

### ISSUE THREAD

**Issue by Beeeeeans** [terjeio/ioSender#286]
When I manually switch the spindle on, it functions as expected but the radio button bounces back to off. To switch the spindle off, I have to click the CW button then Off. The button then bounces back to CW, and to turn on I have to hit off then CW again.

If I run a program, the spindle turns on and off as expected but doesnt change state in the UI until the program finishes and the spindle displays CW.

Behaviour only happens with the spindle enable pin inverted (Which I need). Using a PicoBob and this is repeatable across every version of ioSender I've tried, and any firmware I've tried, on three different computers so far 🤔

**Comment by terjeio** [comment]
Fix committed for the RP2040 grblHAL driver.
