### ISSUE TITLE
IOSender crash when start with door opened.

### ISSUE THREAD

**Issue by RDS356** [terjeio/ioSender#290]
Using the feature 'OPTION(SafetyDoor "Safety door enable" ON)' if you start iosender and this condition is true, it crash.

![door](https://user-images.githubusercontent.com/25726497/233797584-d388565e-f053-4d78-a95c-0a65cc48e093.png)

![door1](https://user-images.githubusercontent.com/25726497/233797583-ef7fcf58-0ad6-41ef-af84-833270add159.png)

**Comment by terjeio** [comment]
The [latest edge version](http://www.io-engineering.com/downloads) 2.0.43p2 should be ok - you can try it?

**Comment by RDS356** [comment]
> The [latest edge version](http://www.io-engineering.com/downloads) 2.0.43p2 should be ok - you can try it?

Hi Terje.
Yes, off course i can.

**Comment by RDS356** [comment]
The crash problem has solved, but another strange think is happening.
After the process the IOsender is reporting in inches, but is not his my option.
Look the pictures bellow , the sequence of open, reset and jog.

If I start with door closed IOsender do not report in inches.
Thank you.
![1](https://user-images.githubusercontent.com/25726497/234976013-f14c4eeb-4402-42a1-81b3-39c4b8066f0d.png)
![2](https://user-images.githubusercontent.com/25726497/234976017-29bbd333-1a29-49bf-b523-95df33e4bb51.png)
![3](https://user-images.githubusercontent.com/25726497/234976021-d031a37f-5fe0-4a88-be43-d47abfc25eda.png)
![4](https://user-images.githubusercontent.com/25726497/234976022-bf66ea5f-1ceb-4fc2-b206-96e48a4bef09.png)

**Comment by terjeio** [comment]
Oops, door close behaves differently depending on parking mode on/off. I have uploaded a new edge version that hopefully works...

**Comment by RDS356** [comment]
> Oops, door close behaves differently depending on parking mode on/off. I have uploaded a new edge version that hopefully works...

Worked perfectly... Thank you Again.
Will new version of IOsender come with this correction ?
Regards, 
Reinaldo de Souza

**Comment by terjeio** [comment]
> Will new version of IOsender come with this correction ?

Yes, edge versions are prereleases.
