### ISSUE TITLE
The cycle start clicking has no effect

### ISSUE THREAD

**Issue by Creat-new** [terjeio/ioSender#291]
When I open it, clicking on manual feed can run normally, but clicking on cycle start does not work. I have tried restarting, reconnecting, and other methods. Can you tell me why? Thank you very much

**Comment by phil-barrett** [comment]
Do you have a GCode program loaded?

**Comment by Creat-new** [comment]
yes，just like this
![image](https://user-images.githubusercontent.com/108221168/234501404-373e2a04-47bc-47cd-a7fb-b1edd8ed3b76.png)
![image](https://user-images.githubusercontent.com/108221168/234501474-4875561d-2a89-4a96-b228-3efbcf533a44.png)

**Comment by Creat-new** [comment]
I tried to directly control with the G0 Z5 command and found that it could be controlled. I wonder if the iosender did not send any commands @phil-barrett

**Comment by phil-barrett** [comment]
maybe some details would help - which processor? any plug-ins?  How is the controller set up? (external buttons, limit switches, etc...).

**Comment by RDS356** [comment]
Is there any msg on console ?

**Comment by terjeio** [comment]
> I wonder if the iosender did not send any commands

A star `*` is shown in front of each gcode block sent, this changes to `ok` when the controller acknowledges reception.
If you enable _Agressive buffering_ in _Settings App_ the sender will fill the controller buffer before waiting for acknowledge from the controller. A grblHAL controller typically has a 1Kbyte buffer, legacy Grbl only 128 bytes.
Note that Grbl v0.9 or non-Grbl controllers are not supported by the sender.

**Comment by Creat-new** [comment]
I think it's my problem, I'm very sorry. Based on your prompt, I have resolved the problem. Thank you again @phil-barrett @terjeio
