### ISSUE TITLE
No support for GRBL on Arduino Nano?

### ISSUE THREAD

**Issue by Dexus** [terjeio/ioSender#301]
I have a china clone of an Arduino Nano with CH3xx but I'm not able to connect to it.
![Screenshot 2023-06-15 094249](https://github.com/terjeio/ioSender/assets/1674289/c66c0318-2819-44b8-b975-e20080c5c0f8)

![Screenshot 2023-06-15 094330](https://github.com/terjeio/ioSender/assets/1674289/41934ad6-e617-404e-9952-62a5f5c05f23)

**Comment by terjeio** [comment]
Odd, are you sure that no other program has the connection open?

**Comment by terjeio** [comment]
Delete App.config and try again, same issue?

**Comment by terjeio** [comment]
[This question](https://stackoverflow.com/questions/76158517/serial-to-usb-cable-ch340-new-driver-not-functioning-with-c-sharp-applicatio) could be a clue? It seems that I do not have any CH340 based boards to test with so I am kind of stuck when it comes to debugging this. My Mega and Due are both genuine boards with Atmel USB<>UART chips and they work fine, and the CP210x based ESP32 board does as well.

**Comment by Dexus** [comment]
Hmm, looks like that could be a clue. But wired that it works with other programs fine... only ioSender does not work currently.
