### ISSUE TITLE
Camera offset is not correct

### ISSUE THREAD

**Issue by Anga42** [terjeio/ioSender#307]
Hi,
when I push the "move camera to spindle button" in the camera window,
the distance is not the same like the one in the settings window.
E.g. I set an cam X offset of -48.2 and Y of 44.6mm and the movment is about in X-80 and Y75mm...

Best regards!

**Comment by terjeio** [comment]
Seems like this could be due to the offset beeing applied twice (or more) after a soft reset.
Try the latest [edge version](http://www.io-engineering.com/downloads) and report back.

**Comment by Anga42** [comment]
With the ioSender Edge 2.0.43p6 it's working fine! Thanks a lot for the support.

**Comment by Anga42** [comment]
With the ioSender Edge 2.0.43p6 it's working fine! Thanks a lot for the support!
