### ISSUE TITLE
Nothing stop program when my e-stop active

### ISSUE THREAD

**Issue by rmaltais** [terjeio/ioSender#312]
Hi,
My E-Stop button seems to work fine. When I press it, the 'E' status turns red. When I start an empty test program and press the e-stop, the program continues without any constraint and nothing happens. I have no alerts. I use GRBLHAL STM32F1XX driver.

**Comment by terjeio** [comment]
Driver bug, [fix commited](https://github.com/grblHAL/STM32F1xx/commit/64a007c0bcb0b47bebade60042e34419aac9bc6a),
