### ISSUE TITLE
Establish reference offset - probe fail

### ISSUE THREAD

**Issue by rmaltais** [terjeio/ioSender#313]
When i tried to setting reference, when message appear for assert probe, on second start nothing do. A message in status show probe fail. I can't see the verbose console because le tab is ot enable. I can't do anything else.
If i bypass the assert probe, the first touch move then on second move, the probe touch and fail message again in status. The probe didn't want to move and i can't go on control again. In this case, i have no choice and must close prgram.

Sorry my poor english, i'm canadian french. Hope you understand this poblem. Use a  GRBLHAL STM32F1XX driver.
My probe is NO and close on GND.

For more détail this is a verbose console during my problem:
`ok
<Idle|MPos:-14.300,-279.666,-55.787|FS:0,0|Pn:PHS>
PM:ok
G1F500Z1
ok
<Run|MPos:-14.300,-279.666,-55.700|FS:398,0|Pn:PHS>
PM:ok
G38.2F25Z-2
<Run|MPos:-14.300,-279.666,-54.800|FS:0,0|Pn:HS>
<Run|MPos:-14.300,-279.666,-54.857|FS:25,0|Pn:HS>
<Run|MPos:-14.300,-279.666,-54.945|FS:25,0|Pn:HS>
<Run|MPos:-14.300,-279.666,-55.030|FS:25,0|Pn:HS>
<Run|MPos:-14.300,-279.666,-55.112|FS:25,0|Pn:HS>
<Run|MPos:-14.300,-279.666,-55.197|FS:25,0|Pn:HS>
<Run|MPos:-14.300,-279.666,-55.280|FS:25,0|Pn:HS>
<Run|MPos:-14.300,-279.666,-55.370|FS:25,0|Pn:HS|WCO:-178.084,-238.144,-58.623>
<Run|MPos:-14.300,-279.666,-55.452|FS:25,0|Pn:HS>
<Run|MPos:-14.300,-279.666,-55.537|FS:25,0|Pn:HS>
<Run|MPos:-14.300,-279.666,-55.620|FS:25,0|Pn:PHS>
ok
PM:ok
$TLR
$G
G90
Probing failed
<Idle|MPos:-14.300,-279.666,-55.658|FS:0,0|Pn:PHS>
ok
[GC:G38.2 G54 G17 G21 G91 G94 G49 G98 G50 M5 M9 T0 F25 S0.]
ok
ok
<Idle|MPos:-14.300,-279.666,-55.658|FS:0,0|Pn:PHS|H:1,7|TLR:1>
<Idle|MPos:-14.300,-279.666,-55.658|FS:0,0|Pn:PHS>
<Idle|MPos:-14.300,-279.666,-55.658|FS:0,0|Pn:PHS|Ov:100,100,100>
<Idle|MPos:-14.300,-279.666,-55.658|FS:0,0|Pn:PHS|WCO:-178.084,-238.144,-58.623>`

**Comment by terjeio** [comment]
What is your $10 setting? _Probe coordinates_ must be added to the status report but I can't see them in the log.

![image](https://github.com/terjeio/ioSender/assets/20260062/1de09d8c-519b-4c8b-ac98-eb6f054bc430)

**Comment by rmaltais** [comment]
Hi,

I don't know is the reason of my problem. After activate probe coordinate like you explain, my probe work perfecfectly now. if is the reason because, thank for your help. All work fie now!

**Comment by rmaltais** [comment]
Thank for help
