### ISSUE TITLE
Big impossible feature request

### ISSUE THREAD

**Issue by crackinx** [terjeio/ioSender#323]
Might not even be an iosender thing or a grblhal thing, but I was thinking would it be possible to be able to hook up a 4th rotary axis as it's own stand alone device instead of needing a controller with another available axis? Either linking it with grblhal wit uart or i2c, or having iosender connect to 2 serial devices to control the rotary axis independently. Might be a huge under taking, but would be worth it to me to just be able to plug in the stand alone rotary axis.

**Comment by terjeio** [comment]
With synchronized motion? Forget it, even if you paid me I would not do that.
A 4+ axis controller is not expensive, cheapest is around USD 15...

**Comment by crackinx** [comment]
That's fair, was just an idea, mostly because I have everything I would need to build it laying around without needing to spend money and re-build my controller box with a new board.
