### ISSUE TITLE
ioSender.XL?

### ISSUE THREAD

**Issue by gharbarka** [terjeio/ioSender#334]
I would like to install ioSender on my PC. There are 2 versions in the .zip list with one on them being referred to as XL.

I have scanned the past issues titles as well as the wiki but I could not find any reference.

Can somebody please explain the differences?

**Comment by phil-barrett** [comment]
ioSender:

**Comment by phil-barrett** [comment]
ioSender. you have to open the jog panel to jog with the mouse.
![image](https://github.com/terjeio/ioSender/assets/16570958/30195f81-0826-4298-9af0-c46354a2b0b4)

ioSender XL gets rid of the jog panel and has the controls always present on the main panel.
![image](https://github.com/terjeio/ioSender/assets/16570958/adf401fe-679b-428b-b1c0-763da5a98c92)

**Comment by gharbarka** [comment]
Gosh...that fast. Thank you.
