### ISSUE TITLE
Feature request - Continuous jogging

### ISSUE THREAD

**Issue by EricB420** [terjeio/ioSender#337]
Would there be a way to add a "Continuous" jogging distance, meaning the machine will continue jogging as long as the button is pressed?
Thanks in advance and looking forward to the next revisions of this wonderful sender!
Eric

**Comment by terjeio** [comment]
See [this wiki page](https://github.com/terjeio/ioSender/wiki/Setup-and-configuration).

**Comment by EricB420** [comment]
Aaah I missed that :-). Thank you !
