### ISSUE TITLE
G41/G42 Cutter Compensation

### ISSUE THREAD

**Issue by gharbarka** [terjeio/ioSender#342]
I could not find any reference in the wiki or the discussions pages of ioSender and the grblHAL these 2 commands. I understand these are not implemented.

Is there any intention to implement these? If the answer is in the negative, how are people getting around this issue? Thanks.

**Comment by terjeio** [comment]
> Is there any intention to implement these?

It is the longer term plan to do so, perhaps in conjunction with adding support for [G61 and G64](http://linuxcnc.org/docs/2.6/html/gcode/gcode.html#sec:G61-G61_1)?

**Comment by gharbarka** [comment]
Thank you both for your contribution.
