### ISSUE TITLE
Machine moving unexpectedly when on probing page

### ISSUE THREAD

**Issue by imechura** [terjeio/ioSender#373]
Hi I have just started using the probing tab on ioSender. In the past I have used the probe by manually entering gcode and it worked but when I change to the probing page, the machine automatically enters a probing sequence without me hitting the start button. If stop it before it crashes and then use the start button to run an edge finer or center finder sequence then the machine will repeatedly run the probing sequence over and over again sometimes running the machine into its limit switches. I could not find a manual that explained the expected behavior for the probing page. Is what I described what should be expected?

please advise.

**Comment by imechura** [comment]
I’m trying to upload a video but this site is limited to 10mb for a video upload?

**Comment by terjeio** [comment]
Try the latest [edge version](https://www.io-engineering.com/downloads). Ok?

**Comment by imechura** [comment]
Ok, I will try it tomorrow

**Comment by terjeio** [comment]
You may also try to short the cycle start input to ground. If EMI somehow triggers the input it may cause the observed behaviour.

**Comment by imechura** [comment]
It was emf on the floating cycle start pin.
