### ISSUE TITLE
backlash compensation 

### ISSUE THREAD

**Issue by 2kbarra** [terjeio/ioSender#375]
Hi,

I was wondering if there's any plans for backlash compensation within iosender? 

cheers,

**Comment by phil-barrett** [comment]
You set it up in grblHAL, not ioSender.  You have to first generate a build with it enabled and the go into settings to set it up.
![image](https://github.com/terjeio/ioSender/assets/16570958/cb0866a6-f4bc-47b1-b6be-e791b12ce63d)

**Comment by 2kbarra** [comment]
cheers for the reply @phil-barrett, That's exactly what i needed. 

I tested the webui builder on a spare pi pico and now see backlash compensation when connected.
