### ISSUE TITLE
Coordinate system table that easily crashes the program

### ISSUE THREAD

**Issue by hanke-cnc** [terjeio/ioSender#379]
I'm not sure if someone as bored as me will manically click on the coordinate system offset table and crash it.

The trigger condition depends on when an entire row is selected, and then clicking on a certain cell will cause the cell to collapse.

😂
![1](https://github.com/terjeio/ioSender/assets/108179425/4b3898a5-6c51-4ab1-aceb-08ac5f8b2308)

**Comment by terjeio** [comment]
The cell marker goes out of sync with the row marker?  I am not able to replicate that.
