### ISSUE TITLE
Signal Z always on

### ISSUE THREAD

**Issue by RDS356** [terjeio/ioSender#396]
Testing my new board I could see this, Signal Z always on. Is it a error ? What kind of error ?

**Comment by RDS356** [comment]
![iosender](https://github.com/user-attachments/assets/53bd502c-fa4a-4e71-9265-0aac39788007)

**Comment by phil-barrett** [comment]
what happens when you manually trigger the sensor?

**Comment by RDS356** [comment]
My Z limit switch was inverted. Problem solved Thank you...
Regards, 
Reinaldo de Souza
