### ISSUE TITLE
Block Delete Character Invalid when Loading Gcode File

### ISSUE THREAD

**Issue by engigeer** [terjeio/ioSender#408]
I am trying to use the block delete functionality recently added to grblhal. If I understand correctly, enabling this mode via my configured input pin, should then skip execution of all lines of gcode that begin with the block delete character (i.e., forward slash ```/```).

I have verified this function of block delete when sending individual lines of code via the console, but it seems that the block delete character may be failing some validation performed when loading a gcode file.

**Comment by terjeio** [comment]
Try the latest [edge builds](https://www.io-engineering.com/downloads) (p12).

**Comment by engigeer** [comment]
Files seem to be loading correctly in the p12 edge build. Much appreciated!
