### ISSUE TITLE
Question for help for translation?

### ISSUE THREAD

**Issue by einencool** [terjeio/ioSender#50]
Hello @terjeio 
I‘d like to ask, If I/we can help you, translating the Program into other languages?
Maybe you can tell, where the files are located, so that I/we could help you translating it?

Maybe there could be a „Config“ File for the name templates in the future, that could be easily edited.
I‘m not a „pro“ in this, but maybe some of these things can help.
It‘s just a thought, because for some people english it not the best solution, because they don‘t understand it...
Greets
Chris

**Comment by terjeio** [comment]
Thank you for your offer.

Problem is it is not ready for translation yet - I have to go through all code to make it translatable by changing all translatable text to tokens or whatever they call it. I will put it on my todo list and come back to you when ready.
